"""
Data types and schemas for AG-S4-002 / S4 End-to-End data protocol.
Standard library only (dataclasses, typing, math, json).
Strictly validates finite numbers, canonical enums, strict booleans, and temporal monotonicity.
"""

from dataclasses import dataclass, field, asdict
from enum import Enum
import math
from typing import Any, Dict, List, Optional, Tuple


class ActionSpace(str, Enum):
    CARTESIAN_EE_DELTA = "cartesian_ee_delta"
    CARTESIAN_EE_POS = "cartesian_ee_pos"
    JOINT_DELTA = "joint_delta"
    JOINT_POS = "joint_pos"


class ActionUnit(str, Enum):
    M_RAD = "m_rad"          # meters (pos) + radians (rot)
    MM_DEG = "mm_deg"        # millimeters (pos) + degrees (rot)
    RAD = "rad"              # joint radians


class TerminationReason(str, Enum):
    RUNNING = "running"
    SUCCESS = "success"
    TIMEOUT = "timeout"
    COLLISION = "collision"
    CONSTRAINT_VIOLATION = "constraint_violation"
    INVALID_ACTION = "invalid_action"


class ValidationError(ValueError):
    """Raised when record data violates protocol constraints."""
    pass


@dataclass(frozen=True)
class ConstraintKey:
    obstacle_id: str
    robot_link: str
    constraint_type: str

    def to_string(self) -> str:
        return f"{self.obstacle_id}:{self.robot_link}:{self.constraint_type}"

    @classmethod
    def from_string(cls, s: str) -> "ConstraintKey":
        if not isinstance(s, str):
            raise ValidationError(f"Constraint ID must be string, got {type(s).__name__}")
        parts = s.split(":")
        if len(parts) != 3 or not all(p.strip() for p in parts):
            raise ValidationError(
                f"Constraint ID '{s}' does not match expected format 'obstacle_id:robot_link:constraint_type'"
            )
        return cls(obstacle_id=parts[0].strip(), robot_link=parts[1].strip(), constraint_type=parts[2].strip())


@dataclass
class LatencyBreakdown:
    observation_ms: float
    inference_ms: float
    filtering_ms: float
    control_ms: float

    def total_ms(self) -> float:
        return (
            self.observation_ms
            + self.inference_ms
            + self.filtering_ms
            + self.control_ms
        )

    def validate(self) -> None:
        for k, v in asdict(self).items():
            if not isinstance(v, (int, float)) or isinstance(v, bool) or math.isnan(v) or math.isinf(v) or v < 0:
                raise ValidationError(f"Latency field '{k}' must be non-negative finite float, got {v}")

    def to_dict(self) -> Dict[str, float]:
        return {
            "observation_ms": float(self.observation_ms),
            "inference_ms": float(self.inference_ms),
            "filtering_ms": float(self.filtering_ms),
            "control_ms": float(self.control_ms),
            "total_ms": float(self.total_ms()),
        }


@dataclass
class ActionSemantics:
    """
    Three distinct action semantic levels:
    - proposed: raw proposal generated by policy
    - commanded_safe: safe command produced by safety filter (sent to controller)
    - measured_state_delta: actual physical state displacement observed after execution
      (null if unmeasured; strictly never forged).
    """
    proposed: List[float]
    commanded_safe: List[float]
    measured_state_delta: Optional[List[float]] = None

    def validate(self) -> None:
        if not isinstance(self.proposed, list) or not self.proposed:
            raise ValidationError("proposed action must be a non-empty list")
        if not isinstance(self.commanded_safe, list) or not self.commanded_safe:
            raise ValidationError("commanded_safe action must be a non-empty list")
        if len(self.proposed) != len(self.commanded_safe):
            raise ValidationError(
                f"Length mismatch: proposed ({len(self.proposed)}) vs commanded_safe ({len(self.commanded_safe)})"
            )
        for i, val in enumerate(self.proposed):
            if not isinstance(val, (int, float)) or isinstance(val, bool) or math.isnan(val) or math.isinf(val):
                raise ValidationError(f"proposed action contains invalid element at index {i}: {val}")
        for i, val in enumerate(self.commanded_safe):
            if not isinstance(val, (int, float)) or isinstance(val, bool) or math.isnan(val) or math.isinf(val):
                raise ValidationError(f"commanded_safe action contains invalid element at index {i}: {val}")
        if self.measured_state_delta is not None:
            if not isinstance(self.measured_state_delta, list):
                raise ValidationError("measured_state_delta must be list or None")
            if len(self.measured_state_delta) != len(self.commanded_safe):
                raise ValidationError(
                    f"Length mismatch: measured_state_delta ({len(self.measured_state_delta)}) "
                    f"vs commanded_safe ({len(self.commanded_safe)})"
                )
            for i, val in enumerate(self.measured_state_delta):
                if not isinstance(val, (int, float)) or isinstance(val, bool) or math.isnan(val) or math.isinf(val):
                    raise ValidationError(f"measured_state_delta contains invalid element at index {i}: {val}")


@dataclass
class StepRecord:
    episode_id: str
    scene_seed: int
    policy_call_id: int
    chunk_id: int
    control_step: int
    sim_time: float
    observation_time: float
    proposed_action: List[float]
    commanded_safe_action: List[float]
    measured_state_delta: Optional[List[float]]
    measured_joint_state: Optional[List[float]]
    measured_ee_state: Optional[List[float]]
    action_space: str
    action_unit: str
    is_normalized: bool
    constraint_id: Optional[str]
    is_intervened: bool
    action_valid_mask: List[bool]
    latency_breakdown: LatencyBreakdown
    termination_reason: Optional[str] = TerminationReason.RUNNING.value
    source: str = "synthetic_unit_test"

    def validate(self) -> None:
        # String and seed validation
        if not self.episode_id or not isinstance(self.episode_id, str):
            raise ValidationError("episode_id must be a non-empty string")
        if not isinstance(self.scene_seed, int) or isinstance(self.scene_seed, bool):
            raise ValidationError("scene_seed must be an int")
        if not isinstance(self.policy_call_id, int) or isinstance(self.policy_call_id, bool) or self.policy_call_id < 0:
            raise ValidationError("policy_call_id must be a non-negative int")
        if not isinstance(self.chunk_id, int) or isinstance(self.chunk_id, bool) or self.chunk_id < 0:
            raise ValidationError("chunk_id must be a non-negative int")
        if not isinstance(self.control_step, int) or isinstance(self.control_step, bool) or self.control_step < 0:
            raise ValidationError("control_step must be a non-negative int")

        # Time validation: strictly finite non-negative numbers (reject Inf and NaN)
        if not isinstance(self.sim_time, (int, float)) or isinstance(self.sim_time, bool) or math.isnan(self.sim_time) or math.isinf(self.sim_time) or self.sim_time < 0:
            raise ValidationError("sim_time must be non-negative finite float")
        if not isinstance(self.observation_time, (int, float)) or isinstance(self.observation_time, bool) or math.isnan(self.observation_time) or math.isinf(self.observation_time) or self.observation_time < 0:
            raise ValidationError("observation_time must be non-negative finite float")

        # Validate action semantics
        semantics = ActionSemantics(
            proposed=self.proposed_action,
            commanded_safe=self.commanded_safe_action,
            measured_state_delta=self.measured_state_delta,
        )
        semantics.validate()

        # Validate measured states (if provided, must be all finite numbers)
        if self.measured_joint_state is not None:
            if not isinstance(self.measured_joint_state, list):
                raise ValidationError("measured_joint_state must be a list of floats")
            for idx, val in enumerate(self.measured_joint_state):
                if not isinstance(val, (int, float)) or isinstance(val, bool) or math.isnan(val) or math.isinf(val):
                    raise ValidationError(f"measured_joint_state contains invalid non-finite value at index {idx}: {val}")

        if self.measured_ee_state is not None:
            if not isinstance(self.measured_ee_state, list):
                raise ValidationError("measured_ee_state must be a list of floats")
            for idx, val in enumerate(self.measured_ee_state):
                if not isinstance(val, (int, float)) or isinstance(val, bool) or math.isnan(val) or math.isinf(val):
                    raise ValidationError(f"measured_ee_state contains invalid non-finite value at index {idx}: {val}")

        # Validate action space and unit against canonical enums
        valid_spaces = {s.value for s in ActionSpace}
        if self.action_space not in valid_spaces:
            raise ValidationError(f"Invalid action_space '{self.action_space}', must be one of {valid_spaces}")

        valid_units = {u.value for u in ActionUnit}
        if self.action_unit not in valid_units:
            raise ValidationError(f"Invalid action_unit '{self.action_unit}', must be one of {valid_units}")

        # Validate strict boolean flags
        if not isinstance(self.is_normalized, bool):
            raise ValidationError(f"is_normalized must be a strict bool, got {type(self.is_normalized).__name__}")
        if not isinstance(self.is_intervened, bool):
            raise ValidationError(f"is_intervened must be a strict bool, got {type(self.is_intervened).__name__}")

        # Validate valid mask: must be a list of strict booleans matching proposed_action length
        if not isinstance(self.action_valid_mask, list) or len(self.action_valid_mask) != len(self.proposed_action):
            raise ValidationError(
                f"action_valid_mask length ({len(self.action_valid_mask) if isinstance(self.action_valid_mask, list) else 'non-list'}) "
                f"must match proposed_action length ({len(self.proposed_action)})"
            )
        for i, b in enumerate(self.action_valid_mask):
            if not isinstance(b, bool):
                raise ValidationError(f"action_valid_mask at index {i} must be strict bool, got {type(b).__name__}")

        # Validate constraint_id when intervened
        if self.is_intervened:
            if not self.constraint_id:
                raise ValidationError("constraint_id cannot be empty when is_intervened is True")
            ConstraintKey.from_string(self.constraint_id)
        else:
            if self.constraint_id is not None:
                ConstraintKey.from_string(self.constraint_id)

        # Validate latency breakdown
        if not isinstance(self.latency_breakdown, LatencyBreakdown):
            raise ValidationError("latency_breakdown must be an instance of LatencyBreakdown")
        self.latency_breakdown.validate()

        # Validate termination reason
        if self.termination_reason is not None:
            valid_reasons = {r.value for r in TerminationReason}
            if self.termination_reason not in valid_reasons:
                raise ValidationError(f"Invalid termination_reason '{self.termination_reason}', must be one of {valid_reasons}")

        # Validate source
        if not self.source or not isinstance(self.source, str):
            raise ValidationError("source tag cannot be empty string")

    def to_dict(self) -> Dict[str, Any]:
        return {
            "episode_id": self.episode_id,
            "scene_seed": self.scene_seed,
            "policy_call_id": self.policy_call_id,
            "chunk_id": self.chunk_id,
            "control_step": self.control_step,
            "sim_time": float(self.sim_time),
            "observation_time": float(self.observation_time),
            "proposed_action": [float(x) for x in self.proposed_action],
            "commanded_safe_action": [float(x) for x in self.commanded_safe_action],
            "measured_state_delta": [float(x) for x in self.measured_state_delta] if self.measured_state_delta is not None else None,
            "measured_joint_state": [float(x) for x in self.measured_joint_state] if self.measured_joint_state is not None else None,
            "measured_ee_state": [float(x) for x in self.measured_ee_state] if self.measured_ee_state is not None else None,
            "action_space": str(self.action_space),
            "action_unit": str(self.action_unit),
            "is_normalized": bool(self.is_normalized),
            "constraint_id": str(self.constraint_id) if self.constraint_id is not None else None,
            "is_intervened": bool(self.is_intervened),
            "action_valid_mask": [bool(b) for b in self.action_valid_mask],
            "latency_breakdown": self.latency_breakdown.to_dict(),
            "termination_reason": str(self.termination_reason) if self.termination_reason is not None else None,
            "source": str(self.source),
        }

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> "StepRecord":
        if not isinstance(d, dict):
            raise ValidationError(f"Expected dict for StepRecord.from_dict, got {type(d).__name__}")

        # Strict checks on boolean fields: reject string booleans like "false" or "true"
        is_intervened = d.get("is_intervened")
        if not isinstance(is_intervened, bool):
            raise ValidationError(f"is_intervened must be strict bool, got {type(is_intervened).__name__}: {is_intervened}")

        is_normalized = d.get("is_normalized")
        if not isinstance(is_normalized, bool):
            raise ValidationError(f"is_normalized must be strict bool, got {type(is_normalized).__name__}: {is_normalized}")

        raw_mask = d.get("action_valid_mask")
        if not isinstance(raw_mask, list):
            raise ValidationError("action_valid_mask must be a list")
        for b in raw_mask:
            if not isinstance(b, bool):
                raise ValidationError(f"action_valid_mask must contain strictly bool elements, got {type(b).__name__}: {b}")

        lat_d = d.get("latency_breakdown", {})
        if not isinstance(lat_d, dict):
            raise ValidationError("latency_breakdown must be a dict")

        latency = LatencyBreakdown(
            observation_ms=float(lat_d.get("observation_ms", 0.0)),
            inference_ms=float(lat_d.get("inference_ms", 0.0)),
            filtering_ms=float(lat_d.get("filtering_ms", 0.0)),
            control_ms=float(lat_d.get("control_ms", 0.0)),
        )

        rec = cls(
            episode_id=str(d["episode_id"]),
            scene_seed=int(d["scene_seed"]),
            policy_call_id=int(d["policy_call_id"]),
            chunk_id=int(d["chunk_id"]),
            control_step=int(d["control_step"]),
            sim_time=float(d["sim_time"]),
            observation_time=float(d["observation_time"]),
            proposed_action=d["proposed_action"],
            commanded_safe_action=d["commanded_safe_action"],
            measured_state_delta=d.get("measured_state_delta"),
            measured_joint_state=d.get("measured_joint_state"),
            measured_ee_state=d.get("measured_ee_state"),
            action_space=str(d["action_space"]),
            action_unit=str(d["action_unit"]),
            is_normalized=is_normalized,
            constraint_id=d.get("constraint_id"),
            is_intervened=is_intervened,
            action_valid_mask=raw_mask,
            latency_breakdown=latency,
            termination_reason=d.get("termination_reason"),
            source=str(d.get("source", "synthetic_unit_test")),
        )
        rec.validate()
        return rec
